# Generated by Django 2.2.4 on 2019-08-07 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('town', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_card_recto', models.ImageField(blank=True, null=True, upload_to='pictures/id_card_recto')),
                ('id_card_verso', models.ImageField(blank=True, null=True, upload_to='pictures/id_card_verso')),
                ('vital_card', models.ImageField(blank=True, null=True, upload_to='pictures/vital_card')),
                ('hours_number', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
