# Generated by Django 2.2.4 on 2019-08-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='email',
        ),
    ]
