# Generated by Django 2.2.4 on 2019-08-07 16:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0003_auto_20190807_1755'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserExtention',
        ),
    ]
