# Generated by Django 2.2.4 on 2019-08-08 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20190808_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextention',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='userextention',
            name='hours_number',
            field=models.IntegerField(blank=True, null=True, verbose_name="nombre d'heure effectuée par le salarié"),
        ),
        migrations.AlterField(
            model_name='userextention',
            name='id_card_recto',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/id_card_recto', verbose_name="photo du recto de la carte d'identité"),
        ),
        migrations.AlterField(
            model_name='userextention',
            name='id_card_verso',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/id_card_verso', verbose_name="photo du verso de la carte d'identité"),
        ),
        migrations.AlterField(
            model_name='userextention',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='userextention',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='code postal'),
        ),
        migrations.AlterField(
            model_name='userextention',
            name='town',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='userextention',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='userextention',
            name='vital_card',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/vital_card', verbose_name='photo de la carte vitale'),
        ),
    ]
