# Generated by Django 2.2.4 on 2019-09-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20190808_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextention',
            name='hours_number',
            field=models.FloatField(default=0, null=True, verbose_name="nombre d'heure effectuée par le salarié"),
        ),
    ]
