# Generated by Django 2.2.4 on 2019-09-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20190904_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextention',
            name='hours_number',
        ),
    ]
